### ISSUE TITLE
HTTP ERROR: 503 and BeanCreationException when starting (Windows, java 10)

### ISSUE THREAD

**Issue by mvdw** [suewonjp/civilizer#4]
I am attempting to start civilizer on Windows 10, with the most recent java.
The browser opens, and shows **HTTP ERROR: 503.**
Starting the BAT file from a CMD window shows:

```
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.
c:\Users\Michiel\Programs\civilizer>java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

c:\Users\Michiel\Programs\civilizer>
c:\Users\Michiel\Programs\civilizer>run-civilizer.bat
[ run-civilizer.bat ] Loading Civilizer...
```
and then a bit later:

```
WARN [context.support.AbstractApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in class path resource [datasource-context.xml]: Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in class path resource [datasource-context.xml]: Invocation of init method failed; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
```
etc.
And it ends with:

```
2018-05-07 11:43:45.651:INFO:oejs.ServerConnector:main: Started ServerConnector@60b4c754{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-05-07 11:43:45.651:INFO:oejs.Server:main: Started @12521ms
Launcher : [INFO] Civilizer is running... access to http://localhost:8080/civilizer/app/home
```

**Comment by suewonjp** [comment]
Thank you for reporting it.

Are you using 0.9.0.RC8? Just let me confirm it.

( 0.9.0.RC7 has an issue like that )

**Comment by mvdw** [comment]
No, the version.txt file says 0.9.0.RC7.

**Comment by mvdw** [comment]
Downloading 0.9.0.RC8 now...

**Comment by mvdw** [comment]
OK, that fixed the problem.
Thanks!
